#!/bin/bash
# apachebooster - updateapachebooster                            
#                                                           All rights Reserved.
# https://github.com/itseasy21/ApacheBooster
# This code is subject to the GPL  license. Unauthorized copying is prohibited

export REMOTVERSION=$( /usr/bin/curl -s  https://raw.githubusercontent.com/itseasy21/ApacheBooster/master/version.txt )
export LOCALVERSION=$(cat /usr/local/cpanel/whostmgr/cgi/ApacheBooster/version.txt)
echo "Remote version $REMOTVERSION"
echo "Local version $LOCALVERSION"
if [ $REMOTVERSION ==  $LOCALVERSION ]; then
        echo "You are using the latest version of ApacheBooster."
else
        cd /usr/local/src
        rm -rf /usr/local/src/ApacheBooster*
        wget https://github.com/itseasy21/ApacheBooster/archive/master.zip -O ApacheBooster.zip
        unzip ApacheBooster.zip
        cd ApacheBooster-master/apachebooster
        bash install.sh
        ps aux|grep varnish|awk '{print $2}'|xargs kill -9
        /etc/init.d/httpd restart
       wget -O /usr/local/cpanel/whostmgr/cgi/ApacheBooster/version.txt https://raw.githubusercontent.com/itseasy21/ApacheBooster/master/version.txt
        echo "Upgrade completed"
fi

