#!/bin/bash
# apachebooster - updateapachebooster                           
# Copyright(c) 2011 Ndimensionz, Inc.
#                                                           All rights Reserved.
#                                      https://github.com/itseasy21/ApacheBooster
# This code is subject to the GPL  license. Unauthorized copying is prohibited

export REMOTVERSION=$( /usr/bin/curl -s https://raw.githubusercontent.com/itseasy21/ApacheBooster/master/apachebooster/cgi/ApacheBooster/version.txt )
export LOCALVERSION=$(cat /usr/local/cpanel/whostmgr/cgi/ApacheBooster/version.txt)
echo "Remote version $REMOTVERSION"
echo "Local version $LOCALVERSION"
if [ $REMOTVERSION ==  $LOCALVERSION ]; then
        echo "You are already using latest version."
else
        cd /usr/local/src
        rm -rf /usr/local/src/apachebooster*
        wget -c wget https://github.com/itseasy21/ApacheBooster/archive/master.zip -O ApacheBooster.zip
        unzip ApacheBooster.zip
        cd apachebooster*
        bash install.sh
        ps aux|grep varnish|awk '{print $2}'|xargs kill -9
        /etc/init.d/httpd restart
       wget -O /usr/local/cpanel/whostmgr/cgi/ApacheBooster/version.txt https://raw.githubusercontent.com/itseasy21/ApacheBooster/master/apachebooster/cgi/ApacheBooster/version.txt
        echo "Upgrade completed"
fi

